# Generated by Django 5.0.1 on 2024-03-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=255, unique=True)),
                ("player1", models.CharField(max_length=50)),
                ("player2", models.CharField(max_length=50)),
                ("board_state", models.JSONField(default=list)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
