# Generated by Django 5.0.3 on 2024-03-12 21:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gamemanager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamesession",
            name="active",
        ),
        migrations.RemoveField(
            model_name="gamesession",
            name="board_state",
        ),
    ]
