# Generated by Django 5.0.3 on 2024-03-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamemanager", "0002_remove_gamesession_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="board_state",
            field=models.JSONField(
                default=[[" ", " ", " "], [" ", " ", " "], [" ", " ", " "]]
            ),
        ),
    ]
