# Generated by Django 5.0.3 on 2024-03-12 21:12

import gamemanager.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamemanager", "0003_gamesession_active_gamesession_board_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="board_state",
            field=models.JSONField(default=gamemanager.models.default_board_state),
        ),
    ]
