# Generated by Django 5.0.3 on 2024-03-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamemanager", "0004_alter_gamesession_board_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="last_move",
            field=models.CharField(default=" ", max_length=1),
        ),
    ]
